name: Build

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup FreeBSD VM
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y wget curl git gcc bash gawk gsed node npm
        run: |
          git clone https://github.com/Privoce/vocechat-web
          cd vocechat-web
          npm install
          npm run build
    
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: vocechat-web-freebsd
        path: |
            vocechat-web/dist

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        files: |
              vocechat-web/dist/**/*

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
