name: Go Build

on:
  push:
    branches:
      - main  # 你可以根据需要修改分支名称
  pull_request:
    branches:
      - main  # 你可以根据需要修改分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone repository
      run: git clone https://github.com/naiba/nezha.git

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20  # 确保使用的是正确的 Go 版本

    - name: Verify Go version
      run: go version

    - name: Set GOPATH
      run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        cd nezha
        go mod tidy

    - name: Build
      run: |
        cd nezha/cmd/dashboard  # 进入包含main.go的目录
        go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.16.25"
