name: Go Build

on:
  push:
    branches:
      - main  # 你可以根据需要修改分支名称
  pull_request:
    branches:
      - main  # 你可以根据需要修改分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone repository
      run: git clone https://github.com/naiba/nezha.git

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20  # 你可以根据需要修改 Go 版本

    - name: Build
      run: |
        cd nezha
        go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=0.16.25"
